---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

patchesJson6902:
  - path: elasticsearch-patch.yaml
    target:
      group: elasticsearch.k8s.elastic.co
      version: v1
      kind: Elasticsearch
      name: issue-4137-reproduction
      namespace: issue-4137-reproduction
