---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: issue-4137-reproduction

commonLabels:
  app: issue-4137-reproduction

resources:
  - elasticsearch.yaml
  - kibana.yaml
  - storageclasses.yaml
  - elasticsearch.podsecuritypolicy.yaml
  - elasticsearch.serviceaccount.yaml
  - psp:elasticsearch.role.yaml
  - psp:elasticsearch.rolebinding.yaml

configurations:
  - kustomizeconfig.yaml
