---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:elasticsearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:elasticsearch
subjects:
- kind: ServiceAccount
  name: elasticsearch
