---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:elasticsearch
rules:
- apiGroups:
  - extensions
  resourceNames:
  - elasticsearch
  resources:
  - podsecuritypolicies
  verbs:
  - use
